server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      database: xc_cms
      uri: mongodb://root:123@localhost:27017

  freemarker:
    cache: false
    settings:
      template_update_delay: 0
